### ISSUE TITLE
Tutorial recommended packages doesn't work

### ISSUE THREAD

**Issue by zorrobyte** [TelescopeJS/nova-docs#8]
http://nova-docs.telescopeapp.org/tutorial-framework.html#Set-Up

```W20170130-15:26:12.592(-5)? (STDERR) /Users/rossfisher/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170130-15:26:12.592(-5)? (STDERR) 						throw(ex);
W20170130-15:26:12.592(-5)? (STDERR) 						^
W20170130-15:26:12.593(-5)? (STDERR) 
W20170130-15:26:12.593(-5)? (STDERR) TypeError: Cannot read property 'call' of undefined
W20170130-15:26:12.593(-5)? (STDERR)     at getComponent (packages/nova:lib/lib/components.js:52:10)
W20170130-15:26:12.593(-5)? (STDERR)     at getRoute (packages/nova:lib/lib/routes.js:48:26)
W20170130-15:26:12.593(-5)? (STDERR)     at packages/nova:lib/lib/routes.js:63:20
W20170130-15:26:12.593(-5)? (STDERR)     at Array.map (native)
W20170130-15:26:12.594(-5)? (STDERR)     at populateRoutesApp (packages/nova:lib/lib/routes.js:60:28)
W20170130-15:26:12.594(-5)? (STDERR)     at initNovaRoutesAndApollo (packages/nova:routing/lib/routing.jsx:23:3)
W20170130-15:26:12.594(-5)? (STDERR)     at Function.time (/Users/rossfisher/workspaceMeteor/Telescope/.meteor/local/build/programs/server/profile.js:301:28)
W20170130-15:26:12.594(-5)? (STDERR)     at /Users/rossfisher/workspaceMeteor/Telescope/.meteor/local/build/programs/server/boot.js:304:13
W20170130-15:26:12.594(-5)? (STDERR)     at /Users/rossfisher/workspaceMeteor/Telescope/.meteor/local/build/programs/server/boot.js:345:5
W20170130-15:26:12.594(-5)? (STDERR)     at Function.run (/Users/rossfisher/workspaceMeteor/Telescope/.meteor/local/build/programs/server/profile.js:480:12)```

**Comment by SachaG** [comment]
I'll take a look. Btw, you can always skip this step and just keep all Nova packages, it doesn't really change much.

**Comment by zorrobyte** [comment]
For sure, just want to ensure that new users can quickly pickup Nova which should increase it's userbase :)

**Comment by xavcz** [comment]
It has been updated 👍
